### ISSUE TITLE
Datalad dataset of preprocessed ER and ToM

### ISSUE THREAD

**Issue by NevenaK** [datalad-datasets/human-connectome-project-openaccess#13]
Hello you great Datalad-magicians ✨,

I would very much appreciate one Datalad dataset each of the preprocessed Emotion Recognition & Theory of Mind/Social Cognition task data from the WU-Minn HCP1200 dataset.

The paths would be the following:
Directories for Emotion Recognition
- <sub>/MNINonLinear/Results/tfMRI_EMOTION_*/EVs/*.txt
- <sub>/MNINonLinear/Results/tfMRI_EMOTION_*/Movement_Regressors.txt
- <sub>/MNINonLinear/Results/tfMRI_EMOTION_*/tfMRI_EMOTION_??.nii.gz
- <sub>/MNINonLinear/Results/tfMRI_EMOTION_*/tfMRI_EMOTION_??_SBRef.nii.gz
 

Directories for Theory of Mind / Social Cognition
- <sub>/MNINonLinear/Results/tfMRI_SOCIAL_*/EVs/*.txt
- <sub>/MNINonLinear/Results/tfMRI_SOCIAL_*/Movement_Regressors.txt
- <sub>/MNINonLinear/Results/tfMRI_SOCIAL_*/tfMRI_SOCIAL_??.nii.gz
- <sub>/MNINonLinear/Results/tfMRI_SOCIAL_*/tfMRI_SOCIAL_??_SBRef.nii.gz

Thank you very much 💗

**Comment by adswa** [comment]
Sure :) I've started the build process for both datasets. Once ready, I will push them to https://github.com/datalad-datasets/hcp_emorec_preprocessed and https://github.com/datalad-datasets/hcp_social_preprocessed. They are probably done in about 24 hours - I'll let you know here.

**Comment by NevenaK** [comment]
perfect, thank you!

**Comment by adswa** [comment]
I've pushed the datasets and you can datalad clone them from GitHub. Let us know if you run into issues :-)
