### ISSUE TITLE
Missing data from 3 subjects

### ISSUE THREAD

**Issue by jadecci** [datalad-datasets/human-connectome-project-openaccess#17]
Hi! Similar to #8, I found that the denoised volumetric rsfMRI files are missing for 3 subjects here, which are avaiable from ConnectomeDB directly. These are:

`193239/MNINonLinear/Results/rfMRI_REST2_RL/rfMRI_REST2_LR_hp2000_clean.nii.gz`
`467351/MNINonLinear/Results/rfMRI_REST1_RL/rfMRI_REST1_RL_hp2000_clean.nii.gz`
`705341/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz`

Thanks!

**Comment by adswa** [comment]
to clarify: do you mean
``193239/MNINonLinear/Results/rfMRI_REST2_LR/rfMRI_REST2_LR_hp2000_clean.nii.gz``?  (there is a flipped RL in the subdirectory name)

**Comment by jadecci** [comment]
Oops, sorry. It should be `193239/MNINonLinear/Results/rfMRI_REST2_RL/rfMRI_REST2_RL_hp2000_clean.nii.gz`

**Comment by adswa** [comment]
Please try if it works for you, now @jadecci

**Comment by jadecci** [comment]
It works now! Thanks :)
