### ISSUE TITLE
HCP1200 SmoothedMyelin*gii

### ISSUE THREAD

**Issue by sheyma** [datalad-datasets/human-connectome-project-openaccess#20]
Hi all,

this is a directory request in [datalad-datasets](https://github.com/datalad-datasets) :)

Could you please make a dir for the smoothed myelin maps from HCP1200 for me?

This is what I would like to get per subject:

 \<SUBJID>/MNINonLinear/fsaverage_LR32k/\<SUBJID>**.L.SmoothedMyelinMap.32k_fs_LR.func.gii**
 \<SUBJID>/MNINonLinear/fsaverage_LR32k/\<SUBJID>**.R.SmoothedMyelinMap.32k_fs_LR.func.gii**
 
Alternatively, feel free to point me on how to do it by myself.

Thanks in advance,
Şeyma.

**Comment by loj** [comment]
Hey @sheyma, I've started building the dataset. Once it's ready, I'll let you know. :-)

**Comment by loj** [comment]
The dataset is pushed and you can now datalad clone it from https://github.com/datalad-datasets/hcp_smoothedmyelin

Let us know if you run into issues :-)

**Comment by sheyma** [comment]
crazy! thanks a lot!
