### ISSUE TITLE
Requesting slides of YouTube tutorial

### ISSUE THREAD

**Issue by tashrifbillah** [datalad-datasets/human-connectome-project-openaccess#21]
Hi @adswa , are the slides from [here](https://www.youtube.com/watch?v=pIGFS8XDjco) available somewhere so we can take a look at them statically? ^_^

**Comment by adswa** [comment]
Yes, they are available as HTML and PDF. The PDFs are here:  https://github.com/datalad-handbook/course/tree/master/talks/PDFs

**Comment by tashrifbillah** [comment]
@adswa , I see over a dozen documents there. Could you be a little more specific?

**Comment by adswa** [comment]
https://github.com/datalad-handbook/course/blob/master/talks/PDFs/DebConf.pdf - is this the one you are looking for?

**Comment by tashrifbillah** [comment]
I think so. Thanks. I attended your OHBM lecture by the way ^
