### ISSUE TITLE
Link of human connectome project

### ISSUE THREAD

**Issue by sofievalk** [datalad-datasets/human-connectome-project-openaccess#26]
Hi, I think this link: http://www.humanconnectomeproject.org/ is not the correct link for the HCP S1200 + details on the project. This should be the correct one: https://www.humanconnectome.org/study/hcp-young-adult

cheers,
Sofie

**Comment by adswa** [comment]
cool, thanks much Sofie! I replaced the link, and put you in as an author of the commit in #27
