### ISSUE TITLE
Failed to clone from all attempted sources

### ISSUE THREAD

**Issue by soichih** [datalad-datasets/human-connectome-project-openaccess#3]
I might be missing some step, but I just datalad install-ed this repo and tried to datalad installl / get 1 subject. I couldn't get very far.. as I am seeing these error messages.

```
brlife@wrangler:/mnt/datalad/human-connectome-project-openaccess$ datalad get -r HCP1200
[INFO   ] Installing <Dataset path=/mnt/datalad/human-connectome-project-openaccess> underneath /mnt/datalad/human-connectome-project-openaccess/HCP1200 recursively 
[ERROR  ] Failed to clone from all attempted sources: ['https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100206', 'https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100206/.git', 'ria+http://store.datalad.org#346a3ae0-2c2e-11ea-a27d-002590496000'] [install(/mnt/datalad/human-connectome-project-openaccess/HCP1200/100206)] 
install(error): /mnt/datalad/human-connectome-project-openaccess/HCP1200/100206 (dataset) [Failed to clone from all attempted sources: ['https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100206', 'https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100206/.git', 'ria+http://store.datalad.org#346a3ae0-2c2e-11ea-a27d-002590496000']]
[ERROR  ] Failed to clone from all attempted sources: ['https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100307', 'https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100307/.git', 'ria+http://store.datalad.org#a51b84fc-2c2d-11ea-9359-0025904abcb0'] [install(/mnt/datalad/human-connectome-project-openaccess/HCP1200/100307)] 
install(error): /mnt/datalad/human-connectome-project-openaccess/HCP1200/100307 (dataset) [Failed to clone from all attempted sources: ['https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100307', 'https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100307/.git', 'ria+http://store.datalad.org#a51b84fc-2c2d-11ea-9359-0025904abcb0']]
[ERROR  ] Failed to clone from all attempted sources: ['https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100408', 'https://github.com/datalad-datasets/human-connectome-project-openaccess.git/HCP1200/100408/.git', 'ria+http://store.datalad.org#d3fa72e4-2c2b-11ea-948f-0025904abcb0'] [install(/mnt/datalad/human-connectome-project-openaccess/HCP1200/100408)] 
...
```

Do I need to install the AWS credential manually?

**Comment by adswa** [comment]
Hey @soichih, which version of DataLad do you have installed? To me this output looks as if it might come from a version that is not the most recent (released today, I believe) 0.12.2 version of DataLad.

**Comment by soichih** [comment]
I recently upgraded it to 0.12.1. I didn't know there is already 0.12.2. Do I need to upgrade?

**Comment by adswa** [comment]
Yes, for this dataset 0.12.2 (or higher) is necessary. Here's an excerpt from the [release notes](https://github.com/datalad/datalad/releases/tag/0.12.2) about the relevant features:

> Enhancements and new features
> -  clone (and thus install)
>    - now propagates the reckless mode from the superdataset when
>      cloning a dataset into it. #4037
>    - gained support for ria+<protocol>:// URLs that point to
>      RIA stores. #4022
>    - learned to read "@Version" from ria+ URLs and install that
>      version of a dataset #4036 and to apply URL rewrites
>      configured through Git's url.*.insteadOf mechanism #4064.
>    - now copies datalad.get.subdataset-source-candidate-<name>
>      options configured within the superdataset into the subdataset.
>     This is particularly useful for RIA data stores. #4073

**Comment by soichih** [comment]
Thanks. It's working now!

**Comment by adswa** [comment]
Awesome! :)
