### ISSUE TITLE
datalad get "Unable to access these remotes"

### ISSUE THREAD

**Issue by cbedetti** [datalad-datasets/human-connectome-project-openaccess#34]
Hello,

I can't access the data with `datalad get`. I get either a "Failed to download from any of 2 locations" or "Unable to access these remotes" message.

I'm on Ubuntu and first tried the datalab version available with apt. Here is my output and my datalad wtf

[datalad-wtf-ubuntu-prompt.txt](https://github.com/datalad-datasets/human-connectome-project-openaccess/files/8467386/datalad-wtf-ubuntu-prompt.txt)
[datalad-wtf-ubuntu.txt](https://github.com/datalad-datasets/human-connectome-project-openaccess/files/8467387/datalad-wtf-ubuntu.txt)

I also tried to install datalad in a virtual environment to have the latest version of datalad.

[datalad-wtf-venv-prompt.txt](https://github.com/datalad-datasets/human-connectome-project-openaccess/files/8467389/datalad-wtf-venv-prompt.txt)
[datalad-wtf-venv.txt](https://github.com/datalad-datasets/human-connectome-project-openaccess/files/8467392/datalad-wtf-venv.txt)

Since `datalad get` never asked for my credentials, I also tried to put my them directly in the prompt but I get the same messages

`DATALAD_hcp_s3_key_id=<key>  DATALAD_hcp_s3_secret_id=<secret> datalad get ...`

**Comment by adswa** [comment]
Hi, thanks for opening this issue!
Could you please try to re-clone the dataset in your virtual environment with DataLad ``0.16.x``? From what I remember about the ``0.12.x`` versions of DataLad, ``0.12.4`` *should* work, but its so long ago that I might have forgotten about necessary reconfigurations of the dataset that are only included in more recent versions. If so, I need to update the minimal DataLad version described in the README. 

If you're still not being prompted for credentials afterwards, could you check in your password manager GUI (it could be ``seahorse`` or ``kwallet`` on ubuntu) if there already is any password entry for ``datalad-hcp-s3``? If you were to upgrade git-annex I think you would also be able to see a more informative "403: Access forbidden" error message in case this is a password issue. 

If things don't work, it would also be great to see the output of ``git-annex whereis  release-notes/rfMRI_REST1_preproc.txt`` (run inside ``HCP1200/100206/``, i.e., the subdataset to which the file belongs. E.g., it should look something like this for any given file:

```
(handbook2) adina@muninn in /tmp/human-connectome-project-openaccess/HCP1200/100206 on git:master
❱ git annex whereis release-notes/Diffusion_unproc.txt
whereis release-notes/Diffusion_unproc.txt (1 copy) 
  	80e5c0d2-70b5-4c9e-a30e-4da117505dc6 -- [datalad]

  datalad: s3://hcp-openaccess/HCP_1200/100206/release-notes/Diffusion_unproc.txt
  datalad: s3://hcp-openaccess/HCP_1200/100206/release-notes/Diffusion_unproc.txt?versionId=j9bm9Jvph3EzC0t9Jl51KVrq6NFuoznu
ok
```

**Comment by cbedetti** [comment]
Hi,
It was indeed a keyring problem.
A fix from our IT specialist was to do: `unset DBUS_SESSION_BUS_ADDRESS`
After that, datalab asks for credentials.

**Comment by adswa** [comment]
Thanks for reporting, and glad it works!
