### ISSUE TITLE
Unable to retrieve MovementRegressor.txt and Movement_AbsoluteRMS.txt

### ISSUE THREAD

**Issue by kahinimehta** [datalad-datasets/human-connectome-project-openaccess#36]
Hello, I hope you're well!

I am writing because I am currently unable to datalad get the MovementRegressor.txt and AbsoluteRMSMovement.txt files: 
<img width="1512" alt="Screen Shot 2023-04-26 at 2 34 22 PM" src="https://user-images.githubusercontent.com/68132139/234675954-6594252e-9333-4873-be25-da8e8dfd21aa.png">

I was wondering if you had any guidance for resolving this issue? 

Thanks.

**Comment by adswa** [comment]
Hi @kahinimehta, I've checked the files, and they work fine for me. Can you report what version of DataLad and git-annex you are running (``datalad wtf`` would show you)?

Also, can you check the contents of  ``HCP1200/101410/MNINonLinear/.git/annex/transfer/``? If you find directories in there, try the ``get`` command again after removing them. The lock files that the output you're showing talks about would be in there. Removing them might already fix your issue.

**Comment by kahinimehta** [comment]
Hello! I am using datalad version: 0.14.7 and git-annex version: 8.20210331-g1fb59a63a. I will try removing those directories and re-running `get` - I will keep you posted. Thank you!

Update: This resolved the issue. Thank you!

**Comment by adswa** [comment]
Glad to hear! If you can, consider upgrading your installation of datalad and git annex to something more recent.
