### ISSUE TITLE
Detailed Age Data in S1200 Dataset

### ISSUE THREAD

**Issue by liukai24** [datalad-datasets/human-connectome-project-openaccess#38]
Hello,

I am conducting research on trends across different age groups using the S1200 dataset. However, I noticed that the behavioral data only provides broad age categories, and there doesn't seem to be detailed age information available.

I would greatly appreciate any assistance or suggestions you could provide regarding this issue.

Thank you in advance for your help!

**Comment by adswa** [comment]
Hey, I'm afraid we won't be of any help here - this question is best addressed to the HCP Project itself or looked up in their documentation. We are just providing a way of conveniently obtaining the data. Good luck!
