### ISSUE TITLE
Rename to hcp-openaccess

### ISSUE THREAD

**Issue by yarikoptic** [datalad-datasets/human-connectome-project-openaccess#4]
To stay consistent with the bucket name, and be considerably shorter. HCP is a known acronym in the field anyways.
I am not sure if -openaccess is if any value and actually not misleading since according to osi definition of open, it is not. But for consistency sake, could be kept

**Comment by yarikoptic** [comment]
Shorter length would be much appreciated by datalad users since reported paths are often full paths on the filesystem, and there name of this repository is the default name it would be cloned into

**Comment by mih** [comment]
I dislike the idea to use 3-letter acronyms for special interest (although I have sinned myself in the past). The location in the github organization is not neuro-specific, hence a full name is useful. I used the name that the consortium uses itself for this dataset to avoid future conflict (which includes the openaccess suffix). The cost of providing a target path is minimal IMHO, and does not justify impairing descriptiveness.

**Comment by yarikoptic** [comment]
I am not shy of acronyms at http://datasets.datalad.org/, especially when they are widely known (although today I received local email that HCP is hiring a project manager! HCP was the Himalayan Cataract Project).  Since datasets.datalad.org is largely neuro* I guess I will make this one available as hcp-openaccess to stay consistent with the bucket name.
