### ISSUE TITLE
Missing data 2 subjects (200614, 205119: MNINonLinear/Results/rfMRI_REST1_LR)

### ISSUE THREAD

**Issue by dlarabi** [datalad-datasets/human-connectome-project-openaccess#8]
It seems that the rfMRI_REST1_LR.nii.gz files (in the /human-connectome-project-openaccess/HCP1200/*/MNINonLinear/Results/rfMRI_REST1_LR folder) are missing for 2 subjects in my sample. According to the HCP website, this data should be available for these subjects. Is there a way to add this data? Subject id's are 200614 and 205119. Thanks a lot!

**Comment by adswa** [comment]
Hey @dlarabi, thanks for the bug report. I queried the HCP's S3 bucket, and I can't find the files that you are referring to. Are you sure that this data is downloadable from their data base? 

```
# first subject
╰─➤ datalad ls -Lr 's3://hcp-openaccess/HCP_1200/200008/MNINonLinear/Results/rfMRI_REST1_LR/*.nii.gz'
Connecting to bucket: hcp-openaccess
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication 
[...]
ERROR: No output was provided for prefix 'HCP_1200/200008/MNINonLinear/Results/rfMRI_REST1_LR/*.nii.gz'

# second subject
╰─➤ datalad ls -Lr s3://hcp-openaccess/HCP_1200/205119/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz
Connecting to bucket: hcp-openaccess
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication 
[...]
ERROR: No output was provided for prefix 'HCP_1200/205119/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz'

# a random other subject that has this file
╰─➤ datalad ls -Lr s3://hcp-openaccess/HCP_1200/200008/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz
Connecting to bucket: hcp-openaccess
[INFO   ] S3 session: Connecting to the bucket hcp-openaccess with authentication 
[...]
HCP_1200/200008/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz 2018-08-19T22:36:41.000Z 1007101220 ver:2PZi0NxIz4ejJlAJwrZ99iPueTEW2mdg  acl:<Policy: ccf-aws (owner) = FULL_CONTROL>  http://hcp-openaccess.s3.amazonaws.com/HCP_1200/200008/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz?versionId=2PZi0NxIz4ejJlAJwrZ99iPueTEW2mdg 
```

**Comment by dlarabi** [comment]
Hey @adswa thanks for checking! You are right, that data is not in the S3 bucket. I have successfully downloaded that data from ConnectomeDB though, there it is available for these subjects. I have e-mailed HCP about this. Is there a way around this, so I still would be able to use this data via datalad?

**Comment by adswa** [comment]
@dlarabi thanks a lot for emailing them about it. The best solution would be if this data is added to the S3 bucket because then it is ensured that all users of the data have complied to HCP's data use agreement... @mih, do you see any other way of doing this without breaching their usage terms?

**Comment by mih** [comment]
I am not aware of the exact procedure to obtain individual files via ConnectomeDB. But if there is a URL that we can use to fetch them, we could add it to the dataset. Ideally, it would work with the existing HCP credentials that everyone needs already.

**Comment by dlarabi** [comment]
Would it work via REST? see https://wiki.humanconnectome.org/display/PublicData/How+To+Access+Subject+Data+via+REST

**Comment by adswa** [comment]
thanks for digging this up @dlarabi! @mih, this seems to work indeed. It uses different HCP credentials (not AWS keys, but connectome-db username and password)

```
datalad download-url  https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/100307/experiments/200614_CREST/resources/200614_CREST/files/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz
[INFO   ] Downloading 'https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/100307/experiments/200614_CREST/resources/200614_CREST/files/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz' into '/home/adina/' 
[INFO   ] http session: Authenticating into session for https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/100307/experiments/200614_CREST/resources/200614_CREST/files/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz 
You need to authenticate with 'hcp-db' credentials. https://db.humanconnectome.org/app/template/Login.vm provides information on how to gain access
user: adina

password: 
password (repeat): 
https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/200614/experiments/200614_CREST/resources/20https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/200614/experiments/200614_CREST/resources/200614_CREST/files/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz:   0%| | 2.10M/978M [00:01<08:06, 2.01MB
[...]
/files/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR.nii.gz: 100%|▉| 977M/978M [05:43<00:00, 3.09MB/                                                                                    
download_url(ok): /home/adina/rfMRI_REST1_LR.nii.gz (file)

```

**Comment by adswa** [comment]
@mih shall we add the files via ``download-url``? I can do this, but would need a pointer to where the dataset is hosted (``bulk1:/ds/hcp/super``?) and which store (``bulk1:/ds/hcp/srv``?) the updates would need to be pushed.

**Comment by dlarabi** [comment]
@adswa @mih thanks for testing it! Would be great if this data can be added to the dataset :)

**Comment by dlarabi** [comment]
Thanks again for adding the data! Here is a list of other data (of the ICA-fix rs-and task-sessions) that is also unfortunately missing in the S3 bucket. That data should also be downloadable via REST.

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/199251/experiments/199251_CREST/resources/199251_CREST/files/MNINonLinear/Results/rfMRI_REST2_RL/rfMRI_REST2_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/rfMRI_REST1_RL/rfMRI_REST1_RL_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/208226/experiments/208226_CREST/resources/208226_CREST/files/MNINonLinear/Results/rfMRI_REST1_RL/rfMRI_REST1_RL_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/rfMRI_REST2_LR/rfMRI_REST2_LR_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/213421/experiments/213421_CREST/resources/213421_CREST/files/MNINonLinear/Results/rfMRI_REST2_LR/rfMRI_REST2_LR_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/202820/experiments/202820_CREST/resources/202820_CREST/files/MNINonLinear/Results/rfMRI_REST2_LR/rfMRI_REST2_LR_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/rfMRI_REST2_RL/rfMRI_REST2_RL_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/198451/experiments/198451_CREST/resources/198451_CREST/files/MNINonLinear/Results/rfMRI_REST2_RL/rfMRI_REST2_RL_hp2000_clean.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_WM_LR/tfMRI_WM_LR.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_WM_RL/tfMRI_WM_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/668361/experiments/668361_CREST/resources/668361_CREST/files/MNINonLinear/Results/tfMRI_WM_RL/tfMRI_WM_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_GAMBLING_RL/tfMRI_GAMBLING_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_MOTOR_LR/tfMRI_MOTOR_LR.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_MOTOR_RL/tfMRI_MOTOR_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_LANGUAGE_LR/tfMRI_LANGUAGE_LR.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/214524/experiments/214524_CREST/resources/214524_CREST/files/MNINonLinear/Results/tfMRI_LANGUAGE_LR/tfMRI_LANGUAGE_LR.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_LANGUAGE_RL/tfMRI_LANGUAGE_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_SOCIAL_LR/tfMRI_SOCIAL_LR.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_SOCIAL_RL/tfMRI_SOCIAL_RL.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_EMOTION_LR/tfMRI_EMOTION_LR.nii.gz

https://db.humanconnectome.org/data/archive/projects/HCP_1200/subjects/150928/experiments/150928_CREST/resources/150928_CREST/files/MNINonLinear/Results/tfMRI_EMOTION_RL/tfMRI_EMOTION_RL.nii.gz

**Comment by adswa** [comment]
Thanks a lot for digging all these files up and providing their links @dlarabi! I will add those to the PR that is in progress (#11)

**Comment by adswa** [comment]
the files should be added an accessible. Thanks again @dlarabi for the issue, the REST API links, and your testing :)
